### ISSUE TITLE
Parsing error

### ISSUE THREAD

**Issue by 5nizza** [meyerphi/strix#6]
Seems like `strix` has trouble understanding variables starting with capital letters. (The docs say it supports such though.)

```
$ ~/software/strix/strix -f 'G (r -> F g) && F NoHigh' --ins r
line 1:18 no viable alternative at input 'FN'
org.antlr.v4.runtime.misc.ParseCancellationException
	at org.antlr.v4.runtime.BailErrorStrategy.recover(BailErrorStrategy.java:51)
	at owl.grammar.LTLParser.binaryExpression(LTLParser.java:424)
	at owl.grammar.LTLParser.andExpression(LTLParser.java:313)
	at owl.grammar.LTLParser.orExpression(LTLParser.java:235)
	at owl.grammar.LTLParser.expression(LTLParser.java:183)
	at owl.grammar.LTLParser.formula(LTLParser.java:136)
	at owl.ltl.parser.LtlParser.parse(LtlParser.java:59)
	at owl.cinterface.CLabelledFormula.parse(CLabelledFormula.java:82)
Caused by: org.antlr.v4.runtime.NoViableAltException
	at org.antlr.v4.runtime.atn.ParserATNSimulator.noViableAlt(ParserATNSimulator.java:2026)
	at org.antlr.v4.runtime.atn.ParserATNSimulator.execATN(ParserATNSimulator.java:467)
	at org.antlr.v4.runtime.atn.ParserATNSimulator.adaptivePredict(ParserATNSimulator.java:393)
	at owl.grammar.LTLParser.binaryExpression(LTLParser.java:398)
	... 6 more
```

Version: strix 21.0.0

**Comment by meyerphi** [comment]
You have to quote variables starting with capital letters. The following should work:
`strix -f 'G (r -> F g) && F "NoHigh"'  --ins r`. Otherwise all capital letters are interpreted as LTL symbols.

**Comment by 5nizza** [comment]
thanks!
